### ISSUE TITLE
Error when no issuer URL is configured

### ISSUE THREAD

**Issue by luke-** [humhub-contrib/auth-konnect#3]
1.) Activate Module
2.) Click on "Konnect" in on login page

**Comment by MasterHans** [comment]
@luke- 
This field is required and it can not be empty.

But I made it safe and try to reproduce the issue .. I did not get it...

**Comment by luke-** [comment]
If you activate the module for the first time and have not yet been in the settings, the field is empty.

**Comment by MasterHans** [comment]
> @MasterHans If you activate the module for the first time and have not yet been in the settings, the field is empty.

But you need to fill it before you activate the module.

![image](https://user-images.githubusercontent.com/17376109/107142495-65b33980-6940-11eb-8aa1-4581a9153e1c.png)

**Comment by MasterHans** [comment]
I cleared the cache and at last, reproduce the issue... Starting to fix it

**Comment by MasterHans** [comment]
We need to clear cash before saving new issuerUrl, because the system takes URL from the cache, not from new issueUrl settings...
